Repository exercism/ruby, pull requests merged in 2021-09, with the labels that each got.

#1193 Correct instantiation of instance for BirdCount
  exercises/concept/bird-count/.docs/instructions.md
Labels: x:type/docs

#1194 Bird-Count: disappointing typo
  exercises/concept/bird-count/bird_count_test.rb
Labels: x:type/docs

#1206 Minor correction in introduction.md
  concepts/advanced-enumeration/introduction.md
Labels: x:size/tiny

#1204 Change number_of_wings to wings
  exercises/concept/amusement-park/.docs/introduction.md
Labels: x:size/tiny

#1201 Use `assert_in_delta` when testing float values
  exercises/concept/savings-account/savings_account_test.rb
Labels: x:type/content, x:size/small

#1203 changed instructions to be inline with tests and code stubs
  exercises/concept/log-line-parser/.docs/instructions.md
Labels: x:type/content, x:size/small
