Repository exercism/ruby, pull requests merged in 2023-09, with the labels that each got.

#1566 Fix typo in method name
  exercises/concept/boutique-inventory/.docs/introduction.md
Labels: x:type/docs, x:size/tiny, x:rep/tiny

#1574 Fix range link
  concepts/ranges/about.md
  concepts/ranges/introduction.md
  exercises/concept/chess-game/.docs/introduction.md
Labels: x:rep/tiny

#1576 Integer is class in Ruby
  exercises/concept/chess-game/.docs/hints.md
  exercises/concept/chess-game/.docs/instructions.md
  exercises/concept/chess-game/.docs/introduction.md
Labels: x:size/small, x:rep/small

#1579 Convert backtick (`) admonition fences to tildes (~)
  concepts/basics/about.md
  concepts/multiple-assignment-and-decomposition/about.md
  concepts/multiple-assignment-and-decomposition/introduction.md
  concepts/ranges/about.md
  concepts/ranges/introduction.md
  exercises/concept/chess-game/.docs/introduction.md
  exercises/concept/locomotive-engineer/.docs/instructions.md
  exercises/concept/locomotive-engineer/.docs/introduction.md
Labels: x:size/tiny
