Repository exercism/ruby, pull requests merged in 2024-06, with the labels that each got.

#1686 meetup: sync
  exercises/practice/meetup/.docs/instructions.md
  exercises/practice/meetup/.docs/introduction.md
  exercises/practice/meetup/.meta/config.json
Labels: x:size/tiny

#1696 Adding missing skips to dnd-character exercise
  exercises/practice/dnd-character/dnd_character_test.rb
Labels: x:rep/small

#1697 For tests, expected comes before actual
  exercises/practice/bank-account/bank_account_test.rb
Labels: ready
